[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=3
lib_deps =
  adafruit/Adafruit BMP3XX Library
  bolderflight/Bolder Flight Systems IMU
  mikalhart/TinyGPSPlus
  sandeepmistry/LoRa
  arduino-libraries/SD
  bogde/HX711
